/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.io.BufferedWriter;
import java.io.FileWriter;

/**
 *
 * @author Adnan
 */
public class menu extends javax.swing.JFrame {
    int vip, ekonomi, harga, beli, total, bayar, kembali;
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jurusan = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        rb_vip = new javax.swing.JRadioButton();
        rb_ekonomi = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_bayar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_kembali = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JToggleButton();
        btn_reset = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Travel Bus");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel11.setText("Nama Lengkap");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 20));
        jPanel4.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 270, -1));

        jLabel12.setText("Jenis Kelamin");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 20));
        jPanel4.add(txt_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, -1));

        laki.setBackground(new java.awt.Color(255, 255, 153));
        laki.setText("Laki-laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });
        jPanel4.add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        perempuan.setBackground(new java.awt.Color(255, 255, 153));
        perempuan.setText("Perempuan");
        perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanActionPerformed(evt);
            }
        });
        perempuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                perempuanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                perempuanKeyReleased(evt);
            }
        });
        jPanel4.add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel14.setText("NIK");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 20));

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        jSeparator3.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 20, 450));

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)), "Data Kereta"));
        jPanel6.setForeground(new java.awt.Color(255, 255, 153));

        jLabel15.setText("Tujuan");

        jurusan.setEditable(true);
        jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Solo", "Semarang", "Jogja", " " }));
        jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanActionPerformed(evt);
            }
        });

        jLabel16.setText("Jenis");

        rb_vip.setBackground(new java.awt.Color(255, 255, 153));
        rb_vip.setText("VIP");
        rb_vip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_vipActionPerformed(evt);
            }
        });

        rb_ekonomi.setBackground(new java.awt.Color(255, 255, 153));
        rb_ekonomi.setText("Economi");
        rb_ekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ekonomiActionPerformed(evt);
            }
        });

        jLabel17.setText("Harga");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_ekonomi)
                            .addComponent(rb_vip)
                            .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rb_vip)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_ekonomi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_harga))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 210, 150));

        jSeparator4.setForeground(new java.awt.Color(51, 0, 51));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 400, 20));

        jLabel18.setText("Jumlah Beli");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 90, 20));

        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });
        jPanel4.add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 120, -1));

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        jPanel4.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 120, -1));

        jLabel9.setText("Total Bayar");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 90, 20));

        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        txt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bayarKeyReleased(evt);
            }
        });
        jPanel4.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 120, -1));

        jLabel19.setText("Uang Bayar");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 90, 20));
        jPanel4.add(txt_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 120, -1));

        jLabel20.setText("Kembalian");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 90, 20));

        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        jPanel4.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        btn_reset.setText("Ulangi");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel4.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        text_area.setColumns(20);
        text_area.setRows(5);
        jScrollPane1.setViewportView(text_area);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 380, 140));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanActionPerformed
        // TODO add your handling code here:
        if(jurusan.getSelectedItem().equals("Pilih Jurusan")){
            buttonGroup1.clearSelection();
            txt_harga.setText("");
            
        }else if(jurusan.getSelectedItem().equals("Solo")){
            vip = 20000;
            ekonomi = 10000;
        }else if(jurusan.getSelectedItem().equals("Semarang")){
            vip = 25000;
            ekonomi = 15000;
        }else if(jurusan.getSelectedItem().equals("Jogja")){
            vip = 40000;
            ekonomi = 30000;
        }
        
    }//GEN-LAST:event_jurusanActionPerformed

    private void rb_vipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_vipActionPerformed
        // TODO add your handling code here:
        if(rb_vip.isSelected()){
            txt_harga.setText(String.valueOf(vip));
            rb_ekonomi.setSelected(false);
        }
    }//GEN-LAST:event_rb_vipActionPerformed

    private void rb_ekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ekonomiActionPerformed
        // TODO add your handling code here:
        if(rb_ekonomi.isSelected()){
            txt_harga.setText(String.valueOf(ekonomi));
            rb_vip.setSelected(false);
        }
    }//GEN-LAST:event_rb_ekonomiActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
        beli = Integer.parseInt(txt_jumlah.getText());
        harga = Integer.parseInt(txt_harga.getText());
        total = beli*harga;
        txt_total.setText(String.valueOf(total));
                
    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
        bayar = Integer.parseInt(txt_bayar.getText());
        kembali = Integer.parseInt(txt_total.getText());
        total = beli * kembali;
        txt_kembali.setText(String.valueOf(total));
        
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a = Integer.valueOf(txt_harga.getText());
        b = Integer.valueOf(txt_jumlah.getText());
        c = a*b;
        txt_total.setText("" + c);
                
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void txt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a = Integer.valueOf(txt_bayar.getText());
        b = Integer.valueOf(txt_total.getText());
        c = a - b;
        txt_kembali.setText("" + c);
        
    }//GEN-LAST:event_txt_bayarKeyReleased

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        
        String[] kata = txt_nama.getText().toString().split(" ");
        
        for (int i = 0; i < kata.length; i++) {
            String word = kata[i];
            kata[i] = word.substring(0, 1).toUpperCase() + word.substring(1).toLowerCase();
        }
        String nama = String.join(" ", kata);
        
        String gender;
        if (laki.isSelected()) {
            gender = "Laki-laki";
        }else{
            gender = "Perempuan";
        }
        String noKtp = txt_nik.getText().toString();
        String tuju = jurusan.getSelectedItem().toString();
        String har = txt_total.getText().toString();
        String bay = txt_bayar.getText().toString();
        String kem = txt_kembali.getText().toString();
        
        
        text_area.setText(" Nama \t: " + nama 
                + "\n NIK \t: " + noKtp 
                + "\n Gender \t: " + gender 
                + "\n Tujuan \t: " + tuju
                + "\n Total Bayar \t: " + har
                + "\n Uang \t: " + bay
                + "\n Kembalian \t: " + kem
                        
        );
        try {
            
            FileWriter namafile = new FileWriter("D:/" + noKtp + ".txt");
            BufferedWriter bw = new BufferedWriter(namafile);
            
            bw.write("Nama \t\t: " + nama);
            bw.newLine();
            bw.write("NIK \t\t: " + noKtp);
            bw.newLine();
            bw.write("Gender \t\t: " + gender);
            bw.newLine();
            bw.write("Tujuan \t\t: " + tuju);
            bw.newLine();
            bw.write("Total Bayar \t: " + har);
            bw.newLine();
            bw.write("Uang \t\t: " + bay);
            bw.newLine();
            bw.write("Kembalian \t: " + kem);
            bw.newLine();
            
            
            
            bw.close();
        } catch (Exception e) {
        }
        btn_cetak.setSelected(false);
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
        try{
        if(laki.isSelected()){
            perempuan.setSelected(false);
        }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_lakiActionPerformed

    private void perempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanActionPerformed
        // T
        try{
        if(perempuan.isSelected()){
            laki.setSelected(false);
        }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_perempuanActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        txt_nama.setText("");
        txt_nik.setText("");
        txt_bayar.setText("");
        txt_harga.setText("");
        txt_jumlah.setText("");
        txt_kembali.setText("");
        txt_total.setText("");
        text_area.setText("");
        jurusan.setSelectedItem("");
        rb_vip.setSelected(false);
        rb_ekonomi.setSelected(false);
        laki.setSelected(false);
        perempuan.setSelected(false);
        btn_reset.setSelected(false);
            
        
        
    }//GEN-LAST:event_btn_resetActionPerformed

    private void perempuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perempuanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanKeyReleased

    private void perempuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perempuanKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_perempuanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_cetak;
    private javax.swing.JToggleButton btn_reset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> jurusan;
    private javax.swing.JRadioButton laki;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JRadioButton rb_ekonomi;
    private javax.swing.JRadioButton rb_vip;
    private javax.swing.JTextArea text_area;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kembali;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nik;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
